#!/usr/bin/env python3
###!/home/centos/python_scripts/venvs/experiment/bin/python

import os
# requests provides HTTP API requests
import requests
import sys
from argparse import ArgumentParser

parser = ArgumentParser(description='Get the current weather information for your zipcode')
parser.add_argument('zip', help="zip/postal code to get weather for")
parser.add_argument('--country', default='us', help="zip/postal belongs to, default is 'us'")
args = parser.parse_args()

# expects Openweathermap API to be passed via OWM_API_KEY env variable
api_key = os.getenv("OWM_API_KEY")
if not api_key:
    print("Error: no 'OWN_API_KEY env variable provided")
    sys.exit(1)

# specify the Openweathermap URL for zip based weather
# https://api.openweathermap.org/data/2.5/weather?zip={zip code},{country code}&appid={API key}
url = f"http://api.openweathermap.org/data/2.5/weather?zip={args.zip},{args.country}&appid={api_key}"
# Use requests HTTP request to obtain the current weather
res = requests.get(url)

# verify successful URL request
if res.status_code != 200:
    print(f"Error talking to weather provider: {res.status_code}")
    sys.exit(2)

# print out the returned JSON weather data
print(res.json())
