#!/usr/bin/env python3

import argparse

parser = argparse.ArgumentParser(description='Search for words including partial words')
parser.add_argument('snippet', help='partial (or complete) string to search for in words')
args = parser.parse_args()

snippet = args.snippet.lower()

# open words file and create a list or words
with open ('/usr/share/dict/words') as f:
    words = f.readlines()

