#!/usr/bin/env python3

import argparse

# parse the arguments
parser = argparse.ArgumentParser()
parser.add_argument('filename', help='the file to read')
parser.add_argument('--limit', '-l', type=int, help='number of lines to read')
# default %(prog) is the script name
parser.add_argument('--version', '-v', action='version', version='%(prog)s 1.0')
args = parser.parse_args()
print(args)
